name: flaskSocketIO
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2020.6.24
  - certifi=2020.6.20
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - ncurses=6.2
  - openssl=1.1.1g
  - pip=20.1.1
  - python=3.6.10
  - readline=8.0
  - setuptools=49.2.0
  - sqlite=3.32.3
  - tk=8.6.10
  - wheel=0.34.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - click==7.1.2
    - flask==1.1.2
    - flask-socketio==4.3.1
    - gevent==20.6.2
    - gevent-websocket==0.10.1
    - greenlet==0.4.16
    - itsdangerous==1.1.0
    - jinja2==2.11.2
    - markupsafe==1.1.1
    - python-engineio==3.13.1
    - python-socketio==4.6.0
    - six==1.15.0
    - werkzeug==1.0.1
    - zope-event==4.4
    - zope-interface==5.1.0

